// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'error-prefix'
  | 'pref-apiBaseUrl'
  | 'pref-help'
  | 'prefs-title'
  | 'querying-message'
  | 'rag-query-button-label'
  | 'rag-query-input-placeholder'
  | 'rag-response-placeholder'
  | 'rag-section-header'
  | 'rag-section-sidenav'
  | 'rag-sources-header';
